robot:
  wheel_radius: 0.028 # radius of wheels
  width:  0.028 # width of wheels
  delta_t: 0.1 # in seconds

geometries:
  h_r2c: 0.075 # horizontal displacement of camera wrt robot
  v_r2c: 0.285 # vertical displacement of camera wrt robot
  x_angle: -130 # rotation degrees angle along X intrinsic axis
  y_angle: 0 # rotation degrees angle along Y intrinsic axis
  z_angle: -90 # rotation degrees angle along Z intrinsic axis
  aruco_size: 0.048  # measured in meters



camera:
  y_offset: 0
  z_offset: 0
  y_angle: 0
  exposure_time: 300
  gain: 100

ekf_slam:
  robot_width: 0.137 # width of the robot in meters (from centers of two wheels)
  motor_std: 0.1 # meters
  dist_std: 0.5 # meters
  angle_std: 10 # degrees

